dist: xenial
os:
- linux
- osx
language: c
osx_image: xcode11
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - bazel
  homebrew:
    taps: bazelbuild/tap
    packages: bazelbuild/tap/bazel
install:
- echo "build --conlyopt=-std=c99 --compilation_mode=opt" > $HOME/.bazelrc
- echo "build --disk_cache=$HOME/.cache/bazel/" >> $HOME/.bazelrc
- echo "build --announce_rc" >> $HOME/.bazelrc
- echo "test --test_output=errors" >> $HOME/.bazelrc
before_script:
- mkdir -p "$HOME/.cache/bazel/"
- bazel version
script:
- bazel test //ryu/... //src/...
- bazel run -c opt //ryu/benchmark:ryu_benchmark
- bazel run -c opt //ryu/benchmark:ryu_printf_benchmark -- -samples=200
- bazel test --copt=-DRYU_ONLY_64_BIT_OPS //ryu/...
- bazel run -c opt --copt=-DRYU_ONLY_64_BIT_OPS //ryu/benchmark:ryu_benchmark
- bazel run -c opt --copt=-DRYU_ONLY_64_BIT_OPS //ryu/benchmark:ryu_printf_benchmark -- -samples=200
- bazel test --copt=-DRYU_OPTIMIZE_SIZE //ryu/... //src/...
- bazel run -c opt --copt=-DRYU_OPTIMIZE_SIZE //ryu/benchmark:ryu_benchmark
- bazel run -c opt --copt=-DRYU_OPTIMIZE_SIZE //ryu/benchmark:ryu_printf_benchmark -- -samples=200
- bazel test --copt=-DRYU_OPTIMIZE_SIZE --copt=-DRYU_ONLY_64_BIT_OPS //ryu/...
- bazel run -c opt --copt=-DRYU_OPTIMIZE_SIZE --copt=-DRYU_ONLY_64_BIT_OPS //ryu/benchmark:ryu_benchmark
- bazel run -c opt --copt=-DRYU_OPTIMIZE_SIZE --copt=-DRYU_ONLY_64_BIT_OPS //ryu/benchmark:ryu_printf_benchmark -- -samples=200
